xivintheshell/xivintheshell

src/Game/StatsModifier.ts
=> Dawntrail - Fix Fire 3 Hard Cast

src/Game/Skills.ts, src/changelog.json
I don't think anybody was doing this when building timelines, but if they were they should consider themselves warned
=> add warning when amplifier is used with max polyglot

src/Components/Common.tsx, src/Components/Main.tsx, src/Components/PlaybackControl.tsx, src/Components/SkillSequencePresets.tsx, src/Components/Skills.tsx, src/Components/TimelineCanvas.tsx, src/Components/TimelineEditor.tsx, src/Controller/Controller.ts, src/Controller/PresetLinesManager.ts, src/Controller/Timeline.ts, src/Game/GameConfig.ts, src/Game/GameState.ts, src/Game/Resources.ts, src/Game/Skills.ts, src/sanity.test.js
=> Convert the rest of js files to tsx

src/changelog.json
=> add changelog entry for stacks display

src/Components/Localization.tsx
I’ve decided to take small steps to avoid conflicts.
=> add Japanese translation on Localization.tsx

package-lock.json, package.json, src/Components/Common.tsx, src/Components/DamageStatistics.tsx, src/Components/ImageExport.tsx, src/Components/IntroSection.tsx, src/Components/LoadSave.tsx, src/Components/Main.tsx, src/Components/PlaybackControl.tsx, src/Components/Timeline.tsx, src/Components/TimelineCanvas.tsx, src/Components/TimelineEditor.tsx, src/Components/TimelineMarkers.tsx, src/Controller/Timeline.ts, src/sanity.test.js
[grand todo list](https://github.com/xivintheshell/xivintheshell/issues/36#issue-2568536028)
90% of the way there for this batch of rework, I think. Laid out a lot of information in plain sight hopefully to save some clicks and navigation, but lmk if something just became more confusing...
Here are some screenshots:
"display settings" tab is hidden because there's nothing to show yet. Will probably move over the checkboxes for optional elements in the next PR.
=> Reorganize page layout (2/?)

src/Components/LoadSave.tsx, src/Controller/Controller.ts, src/Game/Buffs.ts
Proof of concept for exporting as a CSV to feed into Amarantine's combat sim (https://github.com/Amarantine-xiv/Amas-FF14-Combat-Sim/).
Notes:
- If we add this feature it should be a new button to not break existing CSV workflows, I just repurposed the frontend code for now because I'm lazy
- Since we use "Fire 3" instead of "Fire III" we need to have a translation pass--I haven't tested this for PCT but I made some capitalization errors ("Thunder In Magenta" vs. "Thunder in Magenta") so we might want to write a helper to normalize ability names anyway
- The sim doesn't support lucid dreaming, and it doesn't do any mana validation
- The sim does support party buffs (which do not need to be added in chronological order), it shouldn't be too hard to add them to the exported CSV based on …
=> [proof of concept] Export to amarantine's combat sim

src/Game/GameState.ts
Appears to be a simple if condition swap introduced during the RDM refactor
=> Fix Buff Calculations

src/Components/PlaybackControl.tsx, src/Game/GameConfig.ts, src/Game/XIVMath.ts
Thanks to Yuyuka for pointing it out. [AkhMorning](https://www.akhmorning.com/allagan-studies/stats/det/#explaining-determination) uses this formula too
=> Make DET use main stat base numbers and default to 440

src/Components/Skills.tsx, src/Game/GameState.ts, src/Style/style.css
Makes skills on CD resemble how they look in game: with the greyed-out image shrinking as the cooldown progresses. I'd love feedback on both visuals and implementation!
=> change the visual of skills on cooldown

src/Components/Buffs.tsx, src/Components/ColorTheme.tsx, src/Components/Jobs/RPR.tsx, src/Components/TimelineCanvas.tsx, src/Game/Common.ts, src/Game/GameState.ts, src/Game/Jobs/RPR.ts
Fixes
- adds DD and AC buff lines to abilities
- fixes speed scaling
=> More misc RPR fixes

src/Components/IntroSection.tsx, src/changelog.json
Not translated yet but here's a draft for how it could look like in English. Hey y'all let me know your thoughts:
* Content suggestions
* Any name(s) I missed? Hey shanzhe will your friend be maintaining SAM? If not, they should probably at least also be included in the list of additional contributors?
* Fix my broken/awkward English
* By what name(s) would you all like to be listed here? Game/github/discord ID? Something else?
shanzhe you can push to this branch directly. Anyone else let us know below 🙏
=> Update acknowledgements section

src/Components/IntroSection.tsx, src/Style/style.css
UI style modification only
before:
after: add hover style
=> Add hover style to the “[DANGER!] clear browser cache and reload” button

src/Components/TimelineEditor.tsx, src/Controller/Record.ts
Suggested by Caro Kann @ Phoenix: https://discord.com/channels/277897135515762698/1307922201726685236/1325637041353916450
=> Add "move end of selection to start of selection" button

src/Components/Common.tsx, src/Components/LoadSave.tsx, src/Controller/Controller.ts
New update includes support for downtime windows and multi-target abilities in the export.
=> Update ama's combat sim compatibility to 7.2

src/Components/DamageStatistics.tsx, src/Controller/DamageStatistics.ts, src/Game/Jobs/SMN.ts, src/changelog.json
=> SMN potency fixes

src/Controller/Common.ts, src/Game/Jobs/BRD.ts, src/Game/Jobs/MCH.ts, src/Game/Jobs/SMN.ts, src/changelog.json
https://na.finalfantasyxiv.com/lodestone/topics/detail/3c12f110983c5f4288d43aa5ac2ed3c022a75b48
=> Patch 7.25 potency changes

src/Components/Common.tsx, src/Controller/Controller.ts, src/changelog.json
Caused by #174
https://discord.com/channels/277897135515762698/1307922201726685236/1384808738145308693
=> Fix jump timestamp target time and display time at boundaries

src/Game/Data/Jobs/PCT.ts
Getting back to it. PCT's turn for action IDs.
=> Add PCT action IDs

src/Components/Main.tsx
bug report on discord: https://discord.com/channels/277897135515762698/1307922201726685236/1404657907408306176
=> Fix links overlapping in firefox
