src/Game/Skills.ts

Reference logs (picked a couple of my own and the current #1 EX1 parse): https://docs.google.com/spreadsheets/d/e/2PACX-1vQ0rZImZ6XEpBN2KHWnpG8GvuKmL_1ueONS-kYI7RiRGHh0zPM0bv-3v5ycpjHgdZnoAlSPkPwl1TCy/pubhtml#
Some flare star casts seem to have an application delay of 0.666, but they seem like outliers. [This chart](https://docs.google.com/spreadsheets/d/1Emevsz5_oJdmkXy23hZQUXimirZQaoo5BejSzL3hZ9I/edit?gid=543259752#gid=543259752) cites 0.62 as the number, so I'm sticking with the value closest to that.
HT2 seems to share an application delay with HT. Since it's a gain on 2 now it might be worth adding, but I'll leave the work of adding it for later.

Update application delays for high thunder/flare star

---

src/Game/GameState.ts
src/changelog.json

When the Enochian timer was paused due to using Umbral Soul, when that timer resumed, the Polyglot timer would get reset to the full 30s. In actual practice the timer just continues ticking as long as Enochian doesn't drop completely.
Moved and conditioned the simulated timer reset to match the way it behaves in-game.

Enochian pause polyglot fix

---

src/Components/IntroSection.tsx
src/Controller/Controller.ts
src/Game/GameConfig.ts

It seems like the actual default values were previously being set in Controller's constructor despite appearing several places throughout the codebase; this refactor unifies everything and makes sure there's only one place to change the default config.
`initialResourceOverrides` is deliberately left out of `DEFAULT_CONFIG` because I'm concerned that `DEFAULT_CONFIG.initialResourceOverrides` would share the same mutable array object. I don't think this will cause issues, but it's worth keeping in mind.

Refactor default GameConfig and add consts for discord links

---

src/Components/ColorTheme.tsx
src/Components/Common.tsx
src/Components/DamageStatistics.tsx
src/Components/IntroSection.tsx
src/Components/LoadSave.tsx
src/Components/Localization.tsx
src/Components/Main.tsx
src/Components/PlaybackControl.js
src/Components/SkillSequencePresets.tsx
src/Components/Skills.js
src/Components/StatusDisplay.js
src/Components/Timeline.tsx
src/Components/TimelineEditor.tsx
src/Components/TimelineMarkerPresets.tsx
src/Game/Potency.ts
src/Game/Resources.ts

This fixes a bunch of warnings that were raised during `npm start`/`npm build` by running `./node_modules/.bin/eslint --fix --ext .js,.jsx,.ts,.tsx` src/`.
Notably, it removes a lot of calls to bind (which [don't work on arrow functions](https://eslint.org/docs/latest/rules/no-extra-bind)) and a couple trivial constructors ([one is generated by default](https://eslint.org/docs/latest/rules/no-useless-constructor)).
I removed a few unused imports, but there's still some variables the linter is reporting as unused that I elected not to touch for now. @miyehn when you get the time, can you check the remaining warnings and either suppress them or remove variables as needed?

Run eslint --fix

---

.github/workflows/precommit.yml
package-lock.json
package.json
src/Components/DamageStatistics.tsx
src/sanity.test.js

Adds a simple test ensuring that no errors are raised when the page renders or the `Sprint` ability (which would exist for all jobs) is clicked.
The `canvas` package is added as a dependency, since it's apparently necessary for the test framework to render a canvas component.
I tried for a bit to get assertions against the DOM after a click/interaction to work, but after trying to fake timers, mock `requestAnimationFrame`, and a few other things, I couldn't get an assertion to properly check the damage table after an ability is used. Ideally we should revisit this if someone has the time, but for now this basic sanity check should be enough. It seems like the `takeEffect` function of the tested skill still isn't being called (I tried adding an error to the function for sprint and it did …

Add sanity test + github action

---

src/Game/Common.ts
src/Game/GameState.ts
src/Game/Skills.ts

* Prevents adding skills to the timeline that haven't been unlocked according to the config's level, even when using presets.
* Throws as "insufficient resources and/or stats mismatch" error.
* Could perhaps be friendlier and convert equivalent buttons (F2->HF2, T3->HT).

Level Syncing - Add Explicit Level Requirements to Skill Usage

---

src/BlmRotations.test.ts
src/Components/DamageStatistics.tsx

This PR adds tests. These test cases use the global controller object (initialized through some magic), hooks into the damage statistics table, and checks the validity of a few basic lines. I did not add any tests for exact potency numbers since I didn't want them to potentially change every patch, but I did check for the presence of modifiers in the damage table.
The tested cases are as follows:
- 1 iteration of the standard rotation: [unaspected] B3 B4 F3 4xF4 para 2xF4 despair FS
- enochian drop during despair cast raises error: B3 F3 4xF4 despair
- enochian drop removes paradox marker: F3 swift B3 [wait 15s]
- F1 has different modifiers depending on gauge state: F1 F1 F1 F1 B3 para F1

Add some tests

---

src/Components/LoadSave.tsx
src/Controller/Controller.ts
src/changelog.json

This PR stops display rendering logic from running during `loadBattleRecordFromFile`, significantly improving page load + timeline import time. `loadSlot` is still unnecessarily called twice in `tryAutoLoad`, but the added latency is no longer super meaningful.
Before/after (n=1, not scientific)
- Page load (with Akairyu's [7.0 TOP timeline](https://discord.com/channels/277897135515762698/1255782490862387360/1284925798364745771) as the active slot): 2150 ms -> 873 ms
- Import timeline from file (again using Akairyu's TOP timeline): 2478 ms -> 108 ms

Avoid rendering during timeline replay

---

src/BlmRotations.test.ts
src/Components/PlaybackControl.js
src/Components/Skills.js
src/Components/Skills.tsx
src/Controller/Common.ts
src/Controller/Controller.ts
src/Controller/DamageStatistics.ts
src/Game/GameConfig.ts
src/Game/GameState.ts
src/Game/Jobs/BLM.ts
src/Game/Jobs/RoleActions.ts
src/Game/Potency.ts
src/Game/Resources.ts
src/Game/Skills.ts
src/Game/XIVMath.ts

This PR creates `BLMState`, a child class of `GameState`. BLM-specific skills and state have been adjusted to match this new format.
All skills now have their effects on the game state encoded in the `onConfirm` and `onApplication` functions. These should be specified either at the skill's declaration site, or for logic shared across many spells, added to a common helper function (`makeGCD_BLM`). While a particular skill's side effects can still be expressed in two different places (the declaration site and the body of `makeGCD_BLM`), it should now be considerably easier to find the logic than before.
Many frontend elements and the controller still make calls to BLM-specific components, like `state.getIceStacks()`, in order to properly render job gauges. For the time being, I've left …

Job state generalization refactors (2/?)

---

src/Components/Skills.tsx
src/Game/GameState.ts
src/Game/Resources.ts

Apparently, the number of stacks is rendered in-game as a font, and there's no sprite (I found a few similar-looking numbers in xivapi but there was no icon for 0). Instead, I picked the browser-default sans serif font and changed the colors accordingly:
- When the number of stacks is not zero, the number is displayed in white text w/ red border.
- When the number of stacks is zero, the number is displayed in red text w/ black border.
I made the drop shadow more intense if the ability is at maximum stacks to contrast better with the non-grayed out ability.
Here's what it looks like for picto (already deployed, unfortunately Pom Muse just has bad contrast with the skininess of the Windows default font)

Add hotbar icon for multi-stack abilities

---

src/BlmRotations.test.ts
src/Components/PlaybackControl.tsx
src/Game/GameState.ts
src/Game/Jobs/BLM.ts
src/Game/Jobs/RoleActions.ts
src/Game/Resources.ts
src/Game/Skills.ts

Simplified resource declarations, similar to the refactor done for skills. Resources should be declared within a job's state declaration file, cooldown durations + stacks are declared with their corresponding skill, and `ResourceState`, `CoolDownState`, and overrides are automatically populated in `GameState`'s constructor.
After this PR, buff durations are retrieved with the `makeResourceAbility` constructor to avoid duplication between overrides and resource declaration. Resources with varying buff duration based on trait level (just Addle) are kind of weird, and currently still follow the old declaration format--we'd have to modify `ResourceInfo` to store a buff's duration as `(Level) => number` instead of `number`. Cooldown lengths that are modified by traits (Manafont, Swiftcast) are …

Simplify resource declarations

---

src/Components/Common.tsx
src/Components/Main.tsx
src/Components/Timeline.tsx
src/Components/TimelineCanvas.tsx
src/Components/TimelineEditor.tsx
src/Components/TimelineMarkerPresets.tsx

I'm using this PR as a space to dump thoughts, notes, screenshots etc. Comments and suggestions welcome.
Tabs might be useful. Currently bootstrapping some ideas:
TODO:

(1/?) Reorganize page layout

---

src/Components/TimelineEditor.tsx
src/Controller/Controller.ts
src/Controller/Record.ts

If moving/deleting a skill in the timeline editor invalidates some later action, the timeline editor will report the name of the offending skill in text, and display a little red arrow next to it in the timeline box. In situations where a change to an early portion of the timeline affects a skill usage far later (possibly multiple minutes away), it can be difficult to identify the issue. Adding an explicit timestamp to the error message helps alleviate this.

Show error timestamp in timeline editor

---

src/Controller/Record.ts
src/changelog.json

shift-clicking an ability timeline now lets you resize the selection around the first chosen selection
<details><summary>demo</summary>
</details>
<details><summary>analogous behavior from google sheets</summary>
</details>
the orange timeline cursor shifting around to always match the start of the selection is a little weird (note that google sheets keeps a selection box on the initially-selected square), but I think it's reasonable to keep this behavior and it would be a bit more effort to change

Add ability to resize ability selections

---

src/BlmRotations.test.ts
src/Game/GameState.ts
src/changelog.json

If Enochian drops midway through a cast, the MP cost of a spell should be checked again at the cast confirm window, and the spell canceled if the MP cost is no longer met.
Two manual test timelines:
- [bad_b3_eno_drop.txt](https://github.com/user-attachments/files/17609177/bad_b3_eno_drop.txt)
(works on main, fails after this PR): this is also added as an automated test; after reaching 0 MP in a fire phase, the B3 cast was free under AF3 but costs 800 MP instead when eno drops, making the cast fail
- [b3_should_be_800_mp.txt](https://github.com/user-attachments/files/17609180/b3_should_be_800_mp.txt) B3 succeeds but consumes 800 MP after the eno drop happens

Check MP cost at cast confirm window

---

src/Components/DamageStatistics.tsx
src/Game/Common.ts
src/Game/GameState.ts
src/Game/Jobs/BLM.ts
src/Game/Jobs/PCT.ts
src/Game/Potency.ts
src/Game/Skills.ts

Non-pot potency modifiers are now declared along with skill declarations for all skills, with the exception of T3/high thunder dot nodes. DoTs are rare enough that I think it's fine to force people to explicitly declare all modifiers for those, and would give a relatively small surface to refactor.
Tested visible potency values for some timelines of both PCT and BLM; these changes are purely cosmetic either way.

PCT merge cleanup - remove Hammer aspect and getPotencyModifiersFromResourceState (2/2)

---

src/BlmRotations.test.ts
src/Components/DamageStatistics.tsx
src/Components/IntroSection.tsx
src/Components/Main.tsx
src/Components/PlaybackControl.tsx
src/Components/Skills.tsx
src/Components/TimelineMarkers.tsx
src/Controller/Common.ts
src/Controller/Controller.ts
src/Controller/DamageStatistics.ts
src/Game/GameConfig.ts
src/Game/GameState.ts
src/Game/Resources.ts
src/Game/Skills.ts
src/PctTraitPotencies.test.ts

Adds dynamic job swapping.
I've punted on UI decisions in this PR ([see discord discussion](https://discord.com/channels/277897135515762698/1255782490862387360/1297036718972600410)), and just added it as a generic config variable, feel free to push to this branch to change @miyehn (or just change it after this is merged).
Notes:
- A new `job` field is added to the `GameConfig` class, and `ShellVersion` has been incremented.
- Changing the configured job won't take effect until "apply and reset" is hit and the timeline is wiped clean, just as with any other configuration variable.
- There's a minor stutter for icons to reload when a job-swapping configuration is applied--it's not super major since it happens pretty fast, but adding a loading spinner or similar would make it look nicer.
- …

Dynamic job swapping

---

src/Components/ColorTheme.tsx
src/Components/TimelineCanvas.tsx
src/Controller/Controller.ts
src/Controller/Timeline.ts

Timeline slot handle:
I kept inactive slot grey because job colors at low transparency either look very dull and hard to differentiate anyway, or too bright and hard to tell if the slot is active or not. 
I'm also proposing some resource color adjustments for PCT referencing the job gauge, mostly checked their contrast against the background to make them readable & recognizable:
(now that I look at it again I think holy could be more blue and slightly darker... but lmk if the general direction looks okay, especially if people are used to the current colors already)

Active timeline slot handle color based on job; PCT resource color adjustments

---

src/Components/Common.tsx
src/Components/PlaybackControl.tsx

After pasting a set link and pressing "load", the job + level + combat stats are set according to the set's specifications. Users still need to hit "apply and reset" for the changes to take effect, to ensure they don't accidentally wipe the current timeline.
Sample etro link (PCT 2.50): https://xivgear.app/?page=sl%7C143f3245-c35b-4391-8b2b-db5cc1a8de9a
Sample xivgear link (BLM 2.42): https://xivgear.app/?page=sl%7C143f3245-c35b-4391-8b2b-db5cc1a8de9a
xivgear's API had a bug that's fixed in their beta branch, so this PR is hitting `betaapi.xivgear.app`. We should just change it to the non-beta version at some point before we announce our new domain (see convo: https://discord.com/channels/277897135515762698/1295863271328452659/1305012062484959263).

Add etro and xivgear import

---

src/Controller/Controller.ts
src/Controller/PresetLinesManager.ts

Trying to add a preset line to a different job causes an error (just shows up in console and doesn't break anything). This PR associates a job with all preset lines, and hides lines that don't belong to the current job.
Only issue is that there's now some layout shift if the skill preset menu is open. If we want to avoid this behavior, we can error if trying to add a line from a different job instead, but I don't think it makes sense to display preset lines if adding them would cause an error.

Filter preset lines by job

---

src/Components/ColorTheme.tsx
src/Components/PlaybackControl.tsx
src/Controller/Common.ts
src/changelog.json

Current RDM, for example:
And a hypothetical situation with multiple warnings:

Can now label jobs as testing and it'll show a warning for users

---

src/Game/Jobs/MCH.ts

Make object once, add to array multiple times, it's still all the same object, because I am in fact a dummy.
Now each punch is a new instance of a Potency, so they snapshot one at a time, like Yoshi-P intended.
Plus some other "fix my own stupid" tweaks.

Fix some errors with MCH, mainly with queen punch potency creation

---

src/Game/Jobs/MCH.ts
src/Game/Skills.ts

Per the job guide:
```
Grants 5 stacks of Overheated, each stack allowing the execution of Blazing Shot or Auto Crossbow.
Duration: 10s
Overheated Effect: Increases the potency of single-target weaponskills by 20
Heat Gauge Cost: 50
Overheated effect only applicable to machinist job actions.
```
The only AoE weaponskill to consume stacks of overheated is autocrossbow
this PR adds an `isCleave?` parameter to the `Weaponskill` type, which is used to determine whether we should
eat a stack or not. There was already special-case handling on autocrossbow to eat a stack, which was leading
to it eating 2 stacks per usage. This fixes that too.

[MCH] Overheated stacks should not be consumed by (most) AoE skills

---

src/Components/Jobs/BLM.tsx
src/Components/Jobs/DNC.tsx
src/Components/Jobs/PCT.tsx
src/Components/Jobs/RPR.tsx
src/Game/Common.ts
src/Game/Constants/BLM.ts
src/Game/Constants/DNC.ts
src/Game/Constants/MCH.ts
src/Game/Constants/PCT.ts
src/Game/Constants/RDM.ts
src/Game/Constants/RPR.ts
src/Game/Constants/SAM.ts
src/Game/Jobs/BLM.ts
src/Game/Jobs/DNC.ts
src/Game/Jobs/MCH.ts
src/Game/Jobs/PCT.ts
src/Game/Jobs/RDM.ts
src/Game/Jobs/RPR.ts
src/Game/Jobs/RoleActions.ts
src/Game/Jobs/SAM.ts
src/Game/Skills.ts
src/Game/Traits.ts
src/Game/XIVMath.ts
src/traits.test.js

Not sure if there's a better way to do this that avoids an apparent circular import between Common and Traits.
I tried to define TraitName elsewhere and only build the map from Trait.ts, but I was running into static initialization errors with `Trait:buildList()` referencing `Common.ts:TraitList` before it was initialized.

Refactor TraitList into Jobs/Common.ts

---

src/BlmRotations.test.ts
src/Components/DamageStatistics.tsx
src/Components/IntroSection.tsx
src/Controller/Controller.ts
src/Controller/DamageStatistics.ts
src/Controller/Record.ts
src/Controller/Timeline.ts
src/RdmRotations.test.ts
src/SamRotations.test.ts
src/changelog.json

* Make stats table only include selected nodes when there is selection
* Make selection summary purple
* When there is only 1 selected node, can now click on it again to unselect it, but still keep the orange cursor at its beginning
Some entries in the DoT Table (gap/override, total ticks) may not always be meaningful when there is selection. I'm not sure what to do with them and just kept them for now.

Make stats tables only include selected nodes when there is selection

---

src/Components/Skills.tsx
src/Controller/Controller.ts
src/Game/Common.ts
src/Game/GameState.ts
src/Game/Jobs/SAM.ts
src/changelog.json

This fixes [this bug](https://github.com/xivintheshell/xivintheshell/pull/82#issuecomment-2526434551), and combines `status` and `nonCdStatus` in `GameState.getSkillAvailabilityStatus`.
While doing the refactor I also removed `validateAttempt` for SAM's meditate because seems like special case handlings elsewhere already achieved the same effect. Lmk if something broke though 🙏

Make SkillReadyStatus able to include multiple unavailable reasons

---

src/Components/Jobs/RPR.tsx
src/Game/Jobs/RPR.ts

fixes a couple of things that were wrong with RPR
- Added timer for immortal sacrifice
- Remove enhanced reapings whenever shroud is exited (7.1 change)
- sacrificium no longer shares a CD with lemure's slice (sometimes relevant in nonstandard bursts)

misc fixes to reaper

---

src/Components/DamageStatistics.tsx
src/Controller/Controller.ts
src/Controller/DamageStatistics.ts
src/Game/Constants/MCH.ts
src/Game/GameState.ts
src/Game/Jobs/DNC.ts
src/Game/Jobs/MCH.ts
src/Game/Jobs/RoleActions.ts
src/Game/Jobs/SAM.ts
src/Game/Skills.ts
src/changelog.json

Flamethrower has it's use-case now: FRU phase 4 optimization. It has the following behavior characteristics:
- Channeled skill like Meditate and Improvisation: all other actions cancel it
- Technically a ground-targeted DoT: It gets a special DoT tic on application
- Flamethrower tics once per second, rather than once every three
Core changes to support this:
- DoT registration with `registerRecurringEffects` can now specify that the core DoT tick handling will exclude that effect (Job code will be expected to deal with it)
- DoT registration can now specify that the DoT is a ground-targeted DoT
- When addDotPotencies is called for a ground-targeted DoT, an extra potency will be added to the node for the special onApplication tick
- When applyDot is called for a ground-targeted DoT, the …

MCH - Add Flamethrower

---

src/Controller/Controller.ts
src/Game/GameConfig.ts
src/Game/Jobs/PCT.ts

Two issues were reported to us after the initial deployment of the keyed data update:
- Timelines with initial cooldown overrides weren't loading
- Spell speed and speed buffs were applying to the recast of motifs and the hammer combo skills inappropriately
This stemmed from two problems:
- The backwards compatibility change to handle mapping the old override string enum names to the keys was only done for resources, despite the `ResourceOverride` class being used for both.
- Now we'll secondarily check the COOLDOWNS object for a matching key if we don't find one in the RESOURCES object
- There were a couple places in PCT's `captureSpellCastTime` and `captureSpellRecastTime` functions that were doing partial string matches on the name of the action, which missed getting updated to compare …

Post keyed data fixes

---

src/Components/Jobs/AST.tsx
src/Components/Jobs/DRK.tsx
src/Components/Jobs/MNK.tsx
src/Components/Jobs/NIN.tsx
src/Components/Jobs/PLD.tsx
src/Components/Jobs/SCH.tsx
src/Components/Jobs/VPR.tsx
src/Components/Jobs/WHM.tsx
src/Game/Jobs/AST.ts
src/Game/Jobs/DRK.ts
src/Game/Jobs/MNK.ts
src/Game/Jobs/NIN.ts
src/Game/Jobs/PLD.ts
src/Game/Jobs/SCH.ts
src/Game/Jobs/VPR.ts
src/Game/Jobs/WHM.ts
src/Game/Jobs/index.ts

Just stubbing out the remaining `StatusPropGenerator` and `GameState` classes for the jobs that haven't been implemented yet. Nothing fancy, just less work for any other new developers that want to contribute.

Boilerplate {Do you need it?}

---

scripts/sps-LL/test.js
src/Controller/Common.ts
src/Game/GameConfig.ts
src/Game/XIVMath.ts
src/changelog.json

Yuyuka found that at spell speed 1047, with ley lines the GCD should be 2.06 as shown in game, not 2.05. So we dug into the formula and found an error.
Both formulas give the same result when there is no haste buff. The old formula could be off by up to 0.01s when there is haste buff (tested with LL so speedModifier=15). The new formula is a slight modification from what's on Allagan Studies, to account for haste buff correctly. And reused my old script to do some sanity checks
To make sure existing files still load, I also bumped `shellVersion` so existing files still use the old formula <-- confirmed by locally loading all files from shanzhe's test corpus.

Corrected gcd formula

---

src/Components/PlaybackControl.tsx
src/Game/Data/Jobs.ts

Mark fully-supported jobs as outdated due to patch 7.2 changes to warn users about instability until we can update them all.
Notes: 
- We probably want a CN translation for the OUTDATED warning content before we push this out.
- We probably don't want to push this out before the servers go down for the patch.
- Submitting as a draft for right now because of these.
I also have no idea what we're going to do about the CN/KR regions lagging behind Global given the scope of at least the BLM changes...

Move TESTING/OUTDATED warning copy into Support Interface

---

src/Components/DamageStatistics.tsx
src/Components/PlaybackControl.tsx
src/Game/GameState.ts
src/Game/Jobs/BLM.ts
src/Game/Jobs/BRD.ts
src/Game/Jobs/MCH.ts
src/Game/Jobs/PCT.ts
src/Game/Jobs/SAM.ts
src/Game/Jobs/SMN.ts
src/Game/Jobs/WAR.ts
src/Game/Resources.ts
src/changelog.json

Made Resource and CoolDown classes more separate by pulling some some functions out of the base abstract class
Got rid of recast time scaling for CDs, and switch to just store number of stacks available + time till next stack
As a result, there are slight changes to some jobs' implementations
* BLM: Ley Lines is now handled in `Game/Jobs/BLM.ts`
* PCT: Tempera Coat and Tempera Grassa - hopefully I changed them right?
* Others: remove redundant function call parameter(s)
Site behavior is the same as before according to some basic manual testing and shanzhe's test corpus. Resource overrides for CDs also still work.
And I slipped in a few translations

Resource and CoolDown refactors

---

src/Game/Jobs/RPR.ts
src/changelog.json

- Fixed `Grim Swathe` incorrectly being replaced with `Lemure's Slice` instead of `Lemure's Scythe`
- `Regress` now usable in enshroud
- Changed order of replacement for `Gibbet`, `Gallows`, and `Guillotine` so that they are replaced by the enshroud versions when both `Enshrouded` and `Executioner` are available (confirmed ingame that this is correct)
- Removed `Perfectio Parata` upon entering enshroud (confirmed ingame that this is correct)

Misc RPR fixes

---

.gitignore
package-lock.json
package.json
src/Components/Changelog.tsx
src/Components/Common.tsx
src/Components/IntroSection.tsx
src/Components/Main.tsx
src/Components/Skills.tsx
src/Controller/Common.ts
src/Style/style.css
src/changelog.json

(branched off #140)
This PR moves the changelog tab out of the intro section, and makes it more prominent. The new changelog opens in a dialog box displaying the 5 most recent entries, or all entries since the user's last view of the changelog, with older entries in an expandable. Additionally, this PR adds boilerplate for localized changelog entries.
Example gif (shows basic behavior, page refresh, and localizable entries):
Internal changes:
- Replaced `react-tooltip` by `@base-ui-components`'s tooltip component. This reduces the overall bundle size, and the JS bundle with both `@base-ui-components/react/tooltip` and `@base-ui-components/react/dialog` is about 100 kB smaller before gzip. Some additional boilerplate is necessary, but component arrangement is mostly easier to reason about. …

More prominent changelog

---

src/Components/Common.tsx
src/Components/Timeline.tsx
src/Components/TimelineEditor.tsx
src/changelog.json

resolves #182
lesson learned: don't ignore type warnings
this does not fully fix the issue, as due to styling hacks for the editor table row, scrolling to an older skill will have the skill be hidden under the header

Fix timeline editor scroll

---

src/Components/PlaybackControl.tsx
src/Game/GameState.ts
src/Game/Jobs/MNK.ts
src/Game/Jobs/NIN.ts
src/Game/Jobs/SAM.ts

Fixes #98. User experience is still not perfect: the haste modification calculation is based on a method call to the active game state, so a dirty job change or level increase/decrease may use the incorrect value. This isn't too difficult to fix in principle, but requires some minor refactoring effort.

Use inherent speed modifiers in GCD display for MNK, NIN, SAM

---

src/Components/PlaybackControl.tsx
src/Game/GameConfig.ts
src/changelog.json

Caro mentioned to me via Discord DM that the FPS tax table tooltip (made for BLM) is confusing on other jobs:
Since no job really deals with caster tax now, there's no point in keeping this table around anymore. I've replaced it with a table that adjusts according to sps/sks and inherent haste of the class:

Replace cast time table with GCD table

---

src/Components/PlaybackControl.tsx
src/Controller/Controller.ts
src/Game/GameConfig.ts
src/__test__/PctTraitPotencies.test.ts

Stealth feature request from Caro to set main stat and WD from xivgear for smoother compatibility with Ama's combat sim. These stats are not exposed via the UI to avoid confusing users, since they currently serve no direct purpose for the Shell.
Also going to do some refactor work on PlaybackControl after this to enable #206. Merging this for now since it was requested by a user.

Set TEN, WD, and main stat in xivgear/etro import

---

README.md
src/Components/ColorTheme.tsx
src/Components/TimelineEditor.tsx

Readme: me and Eshiya we have enough credit in the about section already (and the tool's deviated enough from the original BLM in the Shell), so I'm removing us and putting shanzhe there
Timeline editor:
* Title and footer background color: I changed them to `bgMediumContrast` because it has text on top and `bgHighContrast` might be a bit too close to text color
* Removing alternating row background: I think the table grid already serves the purpose of differentiating all the rows (and each row here is pretty short anyway), so alternating background might be redundant. This is what it looks like after the change:<img width="1217" height="491" alt="image" src="https://github.com/user-attachments/assets/e30aac4a-9636-43fb-96ce-4cecd31deb65" />
If we have concerns, we can make the grid lines …

Misc adjustments

---

src/Components/TimelineCanvas.tsx
src/changelog.json

Got a report by discord DM that dragging the cursor across a timeline button despite pressing mousedown elsewhere in the canvas will trigger the button, which is common with the "clone timeline slot" button when scrolling horizontally. This PR adds a `mouseDownInHitbox` flag that lets handlers check whether the initial mouseDown event's coordinates occurred within the hitbox.

Prevent accidental timeline slot button clicks

---

.github/workflows/precommit.yml
package-lock.json
package.json
src/Components/PlaybackControl.tsx
src/Controller/Controller.ts
src/Controller/Timeline.ts
src/Game/GameConfig.ts
src/changelog.json

Changing jobs in the config panel now changes combat stats, since most jobs do not share stats. The stats used are either the last stats the user set for that job, or one of The Balance's recommended BiS sets for the current patch. Non-gear-related stats (FPS, countdown) are still preserved across job changes as before. The last used sets for a job are stored in the `DT.defaultPartialConfig: {job}` localStorage keys.
`PlaybackControl.tsx` also got a major facelift, and is about 200 lines shorter than before, though it's still pretty long. A lot of awkward manual state synchronization (mostly related to GCD previews) has been cleaned up as a result. Some components have also been broken up to make code easier to read.
The "apply and reset" button is now alayws visible in the config window, …

PlayerConfig refactor

---

src/Components/PlaybackControl.tsx
src/Components/TimelineCanvas.tsx
src/Components/TimelineEditor.tsx
src/Controller/Controller.ts
src/Controller/Record.ts
src/changelog.json

Allows in-place adjustment of configuration stats with an "apply" button, including override resources. Changes to job/level will still force a reset. If the countdown was increased, a "jump" event is prepended to the timeline to ensure actions don't move unexpectedly.
Resolves #206.
Incidental changes:
- Fixed a bug where canvas tooltips sometimes persisted after the mouse cursor left the area.
- Added a message in the timeline editor tab for when there are no skills.

Change configuration without reset
